### ISSUE TITLE
Redis sentinel support

### ISSUE THREAD

**Issue by 97amarnathk** [launchdarkly/go-server-sdk-redis-redigo#16]
How do I integrate connection via redis sentinel ?

* redigo does not support connecting via redis sentinel setup directly. 
* our redis store is configured to run in sentinel mode
* this package has support for redis sentinel https://pkg.go.dev/github.com/FZambia/sentinel
* Is there a way to add this support to the ldSDK ?

**Comment by cwaldren-ld** [comment]
Hi @97amarnathk, the LaunchDarkly SDKs do not support integration with Redis Sentinel at this time. 

It is theoretically possible to add this support to the Go Server SDK using the package you pointed out, or [go-redis](https://github.com/redis/go-redis). 

I have noted your request; however, I cannot speak to our product roadmap.

**Comment by 97amarnathk** [comment]
Is there a guide on how to build a custom LaunchDarkly Persistent store ?

**Comment by cwaldren-ld** [comment]
There's no guide, but this repo could serve as an example of the interface that you must implement. 

We do have an internal project to integrate with `go-redis`, but it's not quite ready for public release yet. 

Our current intention is to release it as a beta, which you could use, but unfortunately I can't promise any timeline for that.

**Comment by cwaldren-ld** [comment]
Hi @97amarnathk, we've made the `go-redis` integration [available for testing here](https://github.com/launchdarkly/go-server-sdk-redis-go-redis). Please try it out and file any issues you may encounter at that repo.
